routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\PagesController;
use App\Http\Controllers\ProfileController;

//ab
use App\Http\Controllers\Ab\PagesController as ABPagesController;

//admin
use App\Http\Controllers\Admin\UsersController;
use App\Http\Controllers\Admin\UploadController;

//products
use App\Http\Controllers\ProductController;
//checkout
use App\Http\Controllers\CheckoutController;

//payment
use App\Http\Controllers\PaymentController;

//orders
use App\Http\Controllers\Admin\OrderController;
//states
use App\Http\Controllers\Admin\StatesController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//home
Route::get('/', [PagesController::class, 'home'])->name('home');

//aboutus
Route::get('about-us', [PagesController::class, 'aboutus'])->name('aboutus');

//aboutus
Route::get('faqs', [PagesController::class, 'faqs'])->name('faqs');

//contactus
Route::get('contact-us', [PagesController::class, 'contactus'])->name('contactus');

//products
Route::get('/products', [ProductController::class, 'index'])->name('product.index');
Route::get('/featured-products', [ProductController::class, 'showProduct'])->name('product.feature');

Route::get('/product/{id}/{slug}', [ProductController::class, 'showProduct'])->name('product.arrangement');

//checkout 
	Route::get('/cart', [CheckoutController::class, 'cart'])->name('cart.index');
	Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout.index');
	Route::post('/checkout/store', [CheckoutController::class, 'store'])->name('checkout.store');
		
//contactUsForm mail admin
Route::post('mail', [PagesController::class, 'contactUsForm'])->name('admin.contactUsForm');


//contact us
Route::get('/contact-us', [ABPagesController::class, 'contactus'])->name('support');

//flush cache
Route::get('/cache-clear', function() {
	Artisan::call('config:cache');
	Artisan::call('cache:clear');
	return "Cache is cleared";
});

Route::get('/migrate', function() {
	Artisan::call('migrate');
	return "Migrate";
});

Route::get('/storage-link', function() {
	Artisan::call('storage:link');
	return "storage:link";
});



//------------------------------------------------------
//------------------------After Login-------------------
//------------------------------------------------------
Route::middleware(['auth', 'verified'])->group(function () {

	//profile page
	Route::get('/profile', [ProfileController::class, 'index'])->name('profile');	
	
	
	Route::get('/zipfile/{order}', [OrderController::class, 'ordersZipFile'])->name('ab.zipfile');
	
	Route::group(['middleware' => ['role:user']], function(){		
		
		// checkout 
		// Route::get('/checkout', [CheckoutController::class, 'index'])->name('checkout.index');
		// Route::post('/checkout/store', [CheckoutController::class, 'store'])->name('checkout.store');
		
		//payment 
		Route::post('/payment/store', [PaymentController::class, 'store'])->name('payment.store');

		//added url prefix
		Route::prefix('ab')->group(function () {
			//profile page
			Route::get('/', [ProfileController::class, 'index'])->name('ab');
			Route::get('/profile', [ProfileController::class, 'index'])->name('ab.profile');
			Route::post('/profile', [ProfileController::class, 'update'])->name('ab.profile.update');
			
			//password
			Route::get('/profile/password', [ProfileController::class, 'password'])->name('ab.profile.password');
			Route::post('/profile/password', [ProfileController::class, 'passwordUpdate'])->name('ab.profile.passwordupdate');
			
			
			//Arrangements
			Route::get('/arrangements', [ABPagesController::class, 'arrangements'])->name('ab.arrangements');
			Route::get('/arrangements/{order}', [ABPagesController::class, 'arrangementShow'])->name('ab.arrangements.show');
			
			//orders
			Route::get('/purchase-orders', [ABPagesController::class, 'orders'])->name('ab.orders');
			Route::get('/purchase-orders/{order}/invoice', [OrderController::class, 'ordersPurchaseInvoice'])->name('ab.purchase_orders.invoice');
			Route::get('/purchase-orders/{order}', [ABPagesController::class, 'orderShow'])->name('ab.orders.show');
			
			//support
			Route::get('/support', [ABPagesController::class, 'support'])->name('ab.support');

		});
	});
	
	

	//added url prefix
	Route::prefix('admin')->group(function () {
		Route::group(['middleware' => ['role:admin']], function(){
			
			//profile page
			Route::get('/', [ProfileController::class, 'index'])->name('admin');
			Route::get('/profile', [ProfileController::class, 'index'])->name('admin.profile');
			Route::post('/profile', [ProfileController::class, 'adminProfileupdate'])->name('admin.profile.update');
			
			//password
			Route::get('/profile/password', [ProfileController::class, 'password'])->name('admin.profile.password');
			Route::post('/profile/password', [ProfileController::class, 'passwordUpdate'])->name('admin.profile.passwordUpdate');
			
			//admin
			//users
			Route::get('/users', [UsersController::class, 'index'])->name('admin.users');
			//edit
			Route::get('/users/edit/{user}', [UsersController::class, 'edit'])->name('admin.users.edit');
			Route::post('/users/update/{user}', [UsersController::class, 'update'])->name('admin.users.update');
			//delete
			Route::delete('/users/{user}', [UsersController::class, 'destroy'])->name('admin.users.destroy');
			
			//difficulty
			Route::resource('/difficulty', App\Http\Controllers\Admin\DifficultyController::class, ['as' => 'admin']);
			
			//instrumentation
			Route::resource('/instrumentation', App\Http\Controllers\Admin\InstrumentationController::class, ['as' => 'admin']);
			
			//composer
			Route::resource('/composer', App\Http\Controllers\Admin\ComposerController::class, ['as' => 'admin']);
			
			//windarranger
			Route::resource('/wind-arranger', App\Http\Controllers\Admin\WindArrangerController::class, ['as' => 'admin']);
			
			//percussionarranger
			Route::resource('/percussion-arranger', App\Http\Controllers\Admin\PercussionArrangerController::class, ['as' => 'admin']);
			
			
			//uploads
			Route::post('/upload', [UploadController::class, 'upload'])->name('admin.upload');
			
			//Arrangements
			Route::resource('/arrangements', App\Http\Controllers\Admin\ArrangementController::class, ['as' => 'admin']);
			
			//orders
			Route::get('/orders', [OrderController::class, 'index'])->name('admin.orders.index');
			Route::get('/orders/{order}', [OrderController::class, 'show'])->name('admin.orders.show');
			
			//admin.mapOfPurchase
			Route::get('/map-of-purchase', [OrderController::class, 'mapOfPurchase'])->name('admin.mapOfPurchase');
			
			//purchase_orders
			Route::get('/purchase-orders', [OrderController::class, 'ordersPurchase'])->name('admin.purchase_orders.index');
			Route::get('/purchase-orders/{order}/invoice', [OrderController::class, 'ordersPurchaseInvoice'])->name('admin.purchase_orders.invoice');
			Route::post('/purchase-orders/generate', [OrderController::class, 'ordersPurchaseGenerate'])->name('admin.purchase_orders.generate');
			Route::post('/purchase-orders/payment_completed', [OrderController::class, 'ordersPurchasePaymentComplete'])->name('admin.purchase_orders.payment_completed');
			Route::get('/purchase-orders/{order}', [OrderController::class, 'ordersPurchaseShow'])->name('admin.purchase_orders.show');
			
			//promocode
			Route::resource('/promocode', App\Http\Controllers\Admin\PromoCodeController::class, ['as' => 'admin']);
			
			//cancelPayment
			Route::post('/paymentCancel', [PaymentController::class, 'paymentCancel'])->name('paymentCancel');
			
			//arrangements type
			Route::resource('/arrangement-type', App\Http\Controllers\Admin\ArrangementTypeController::class, ['as' => 'admin']);
			
			//states
			Route::resource('/states', App\Http\Controllers\Admin\StatesController::class, ['as' => 'admin'])->only('index', 'update');


		});
	});
});

app/Models/WindArranger.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class WindArranger extends Model
{
    use HasFactory;
	
	protected $fillable = [
		'title',
        'status',
        'is_delete',
    ];
}

app/Http/Controllers/Admin/WindArrangerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Validator;
use Illuminate\Http\Request;
use App\Models\WindArranger;

class WindArrangerController extends Controller
{
    public function index(Request $request)
    {
		$title = array(
			'title' => 'WindArranger',
			'active' => 'windArranger'
		);

		$windarrangers = WindArranger::query();
		if(@$request->search){
			$windarrangers = $windarrangers->where('title', 'like', '%'.$request->search.'%');
		}
		if(@$request->status){
			$windarrangers = $windarrangers->where('status', $request->status);
		}
		if(@$request->archive){
			$windarrangers = $windarrangers->where('is_delete', $request->archive);
		}
		else {
			$windarrangers = $windarrangers->where('is_delete', '0');
		}
		
		$windarrangers = $windarrangers->orderBy('id', 'desc')->paginate(pagi());
		
		return view('admin.windarranger.index', compact('title', 'windarrangers'));
    }
	
	public function create()
    {
		$title = array(
			'title' => 'WindaArranger Create',
			'active' => 'windaArranger'
		);
		return view('admin.windarranger.create', compact('title'));
    }
	
	public function store(Request $request)
    {
		$validated = $request->validate([
			'title' => 'required|string|unique:wind_arrangers,title|max:150',
			'status' => 'required',
		]);
		
		$store = new WindArranger;
		$store->title = $request->title;
		$store->status = $request->status;
		$store->save();
		$request->session()->flash('success', "Wind Arranger Created successfully");
        return redirect()->route('admin.wind-arranger.index');
	
	
    }
	
	public function edit(WindArranger $wind_arranger)
    {
		$title = array(
			'title' => 'WindaArranger Edit',
			'active' => 'windaArranger'
		);
		$windarranger = $wind_arranger;
		return view('admin.windarranger.edit', compact('title', 'windarranger'));
    }
	
	
	public function update(Request $request, WindArranger $wind_arranger)
    {
		$validated = $request->validate([
			'title' => 'required|string|max:150|unique:wind_arrangers,title,'.$wind_arranger->id,
			'status' => 'required',
		]);
		$windarranger = $wind_arranger;
		$windarranger->title = $request->title;
		$windarranger->status = $request->status;
		$windarranger->save();
		
		$request->session()->flash('success', "Wind Arranger Updated successfully");
		return redirect()->route('admin.wind-arranger.index');
    }
	
	public function destroy(Request $request, WindArranger $wind_arranger)
    {
		$windarranger = $wind_arranger;
		if($windarranger->is_delete=='1'){
			$windarranger->is_delete = '0';
			$message = "WindaArranger Retrieve";
		}
		else {
			$windarranger->is_delete = '1';
			$message = "WindaArranger Deleted";
		}
		$windarranger->save();
		$request->session()->flash('success', $message);
		return redirect()->route("admin.wind-arranger.index");
    }
}

resources/views/admin/windarranger/create.blade.php
@extends('layouts.app')
@section('content')

<section class="form-section account-section">
	<div class="container-1315">
		<div class="tab-wrappers">
			<div class="tab-content">
				<div class="form-box-inner max-555">
					{!! Form::open(['route' => 'admin.wind-arranger.store']) !!}
					
					@include('admin.windarranger.partials.form')
					
					<div class="form-grouph submit-design twobtns-flex">
						<button class="submit-btn">Submit</button>
					</div>
					{!! Form::close() !!}
				</div>
			</div>
		</div>
	</div>
</section>
	
@endsection	

resources/views/admin/windarranger/edit.blade.php
@extends('layouts.app')
@section('content')

<section class="form-section account-section">
	<div class="pull-right">
		<a href="{{ route('admin.wind-arranger.index') }}" title="Back" class="btn btn-warning btn-icon pull-right"><i class="fa fa-arrow-left"></i></a>
	</div>
	<div class="container-1315">
		<div class="tab-wrappers">
			<div class="tab-content">
				<div class="form-box-inner max-555">
					{!! Form::model($windarranger, ['route' => ['admin.wind-arranger.update', $windarranger->id], 'method' => 'PATCH', ]) !!}
					
					@include('admin.windarranger.partials.form')
					
					<div class="form-grouph submit-design twobtns-flex">
						<button class="submit-btn">Update</button>
					</div>
					{!! Form::close() !!}
				</div>
			</div>
			</div>
	</div>
</section>

@endsection

resources/views/admin/windarranger/index.blade.php
@extends('layouts.app')
@section('content')

<section class="user-information-section">
	<div class="container-1350">
		{!! Form::open(['route' => 'admin.wind-arranger.index', 'method'=>'get']) !!}
		<div class="row">
			<div class="col-lg-3 col-md-6 form-group">
				{!! Form::text('search', request()->search ?? null, ['class' => 'form-control' . ($errors->has('search') ? ' is-invalid' : ''), 'placeholder'=>'Search' ]) !!}
			</div>
			<div class="col-lg-3 col-md-6 form-group">
				{!! Form::select('status', ['1'=>'Active', '0'=>'De-active'], request()->status ?? null, ['class' => 'form-control' . ($errors->has('status') ? ' is-invalid' : ''), 'placeholder'=>'Select status' ]) !!}
			</div>
			<div class="col-lg-2 col-md-4 form-group">
				{!! Form::select('archive', ['0'=>'No', '1'=>'Yes'], request()->archive ?? null, ['class' => 'form-control' . ($errors->has('archive') ? ' is-invalid' : ''), 'placeholder'=>'Archive' ]) !!}
			</div>
			<div class="col-lg-2 col-md-4 form-group">
				<button class="btn btn-primary" type="submit">Search</button>
			</div>
			<div class="col-lg-2 col-md-4 form-group">
				<a href="{{ route('admin.wind-arranger.create') }}" title="Add" class="btn btn-success"><i class="fa fa-plus"></i> Add</a>
				</div>
		</div>
		{!! Form::close() !!}
		
		<div class="user-informtion-table tab-wrappers" id="table-show-sorting">	
			<table class="table" style="width:100%">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Title</th>
                        <th>Status</th>
                        <th>Action</th>
					</tr>
				</thead>
                <tbody>	
					@foreach($windarrangers as $i => $windarranger)
					<tr>
						<td>{{ $i+1 }}</td>
						<td>{{ $windarranger->title }}</td>
						<td>
							@if(@$windarranger->status=='1')
							<span class="label label-success">Active</span>
							@else
							<span class="label label-danger">De-active</span>
							@endif
						</td>
						<td>
							<div class="btn-icon-list">
								<a href="{{ route('admin.wind-arranger.edit', $windarranger->id) }}" class="btn btn-warning btn-icon">
									<i class="fa fa-edit"></i>
								</a>
								
								@if($windarranger->is_delete=='1')
								<a data-method="Delete" data-confirm="Are you sure to retrieve?" href="{{ route('admin.wind-arranger.destroy', $windarranger->id) }}" class="btn btn-danger btn-icon">
									<i class="fa fa-reply"></i>
								</a>
								@else
								<a data-method="Delete" data-confirm="Are you sure to delete?" href="{{ route('admin.wind-arranger.destroy', $windarranger->id) }}" class="btn btn-danger btn-icon">
									<i class="fa fa-trash"></i>
								</a>
								@endif
							</div>
						</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
		<div class="pagination">
			@if(@request()->search || request()->status || request()->archive)
				{{ $windarrangers->appends([
					'search' => request()->search,
					'status' => request()->status,
					'archive' => request()->archive,
				])->links() }}
			@else
				{{ $windarrangers->links() }}
			@endif
		</div>
	</div>
</section>

@endsection			